version: '3'
networks:
  # Default Network ------------------------------------------
  lde-network:
    ipam:
      config:
        - subnet: 192.168.103.0/24

services:
  # Apache ---------------------------------------------------
  apache:
    container_name: apache
    hostname: apache
    restart: ${DOCKER_RESTART}
    build:
      context: ./apache
      dockerfile: ./Dockerfile
      args:
        - EXTRA_CMDS=${EXTRA_CMDS_APACHE}
    ports:
      - "80:80"
    volumes:
      - ./apache/sites:/usr/local/apache2/conf/sites:ro
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env
    networks:
      lde-network:
        ipv4_address: 192.168.103.100

  # Mailhog ---------------------------------------------------
  mailhog:
    container_name: mailhog
    hostname: mailhog
    restart: ${DOCKER_RESTART}
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      lde-network:

  # MySQL ---------------------------------------------------
  mysql:
    container_name: mysql
    hostname: mysql
    restart: ${DOCKER_RESTART}
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
      args:
        - EXTRA_CMDS=${EXTRA_CMDS_MYSQL}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""
    networks:
      lde-network:

  # PHP 8.0 ---------------------------------------------------
  php80-fpm:
    container_name: php80
    hostname: php80
    build:
      context: ./php
      dockerfile: ./80/Dockerfile
      args:
        - EXTRA_CMDS=${EXTRA_CMDS_PHP80}
        - CUSTOM_USER_NAME=${CUSTOM_USER_NAME}
        - CUSTOM_UID=${CUSTOM_UID}
        - CUSTOM_GID=${CUSTOM_GID}
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}

  # PHP 7.4 ---------------------------------------------------
  php74-fpm:
    container_name: php74
    hostname: php74
    build:
      context: ./php
      dockerfile: ./74/Dockerfile
      args:
        - EXTRA_CMDS=${EXTRA_CMDS_PHP74}
        - CUSTOM_USER_NAME=${CUSTOM_USER_NAME}
        - CUSTOM_UID=${CUSTOM_UID}
        - CUSTOM_GID=${CUSTOM_GID}
    ports:
      - "3000:3000" # Browser Sync
      - "3001:3001" # Browser Sync UI
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}

  # PHP 5.6 ---------------------------------------------------
  php56-fpm:
    container_name: php56
    hostname: php56
    build:
      context: ./php
      dockerfile: ./56/Dockerfile
      args:
        - EXTRA_CMDS=${EXTRA_CMDS_PHP56}
        - CUSTOM_USER_NAME=${CUSTOM_USER_NAME}
        - CUSTOM_UID=${CUSTOM_UID}
        - CUSTOM_GID=${CUSTOM_GID}
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}

  # PHPMyAdmin ---------------------------------------------------
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: ${DOCKER_RESTART}
    image: "phpmyadmin"
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=256MB
    links:
      - mysql
    ports:
      - "8080:80"
    networks:
      lde-network:
